Algoritmo "Lista6-7"
Var
   sexo, nome : caractere
   idade, i : inteiro
Inicio
   para i de 1 ate 20 faca
      escreval("Digite seu nome")
      leia(nome)
      escreval("Digite seu sexo")
      leia(sexo)
      escreval("Digite sua idade")
      leia(idade)
      se(sexo="Masculino") e (idade >= 21) entao
         escreval
         escreval(nome)
         escreval
      fimse
   fimpara
Fimalgoritmo