Algoritmo "Lista 3-10"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jefferson leonardo
// Data atual  : 19/10/2021
Var
   n1:inteiro
Inicio
   escreva("Digite um número inteiro: ")
   leia(n1)
   escreval
   se (n1>=1) e (n1<=10)entao
      escreval("O número",n1," está na faixa de 1 a 10")
   senao
      escreval("O número",n1," não está na faixa de 1 a 10")
   fimse
Fimalgoritmo