Algoritmo "Lista 3-13"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jefferson leonardo
// Data atual  : 19/10/2021
Var
   n1,n2:inteiro
Inicio
   escreval("Digite dois números inteiros: ")
   leia(n1,n2)
   escreval
   se (n2%n1=0)entao
      escreval("O segundo número é um divisor do primeiro número informado")
   senao
      escreval("O segundo número não é um divisor do primeiro número informado")
   fimse
Fimalgoritmo