Algoritmo "Lista 3-2"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jefferson leonardo
// Data atual  : 19/10/2021
Var
   capital:caractere
Inicio
   escreva("Qual é a capital do Brasil(de acordo com a norma culta): ")
   leia(capital)
   escreval
   se (capital="Brasília") entao
      escreval("Sua resposta está correta! :)")
   senao
      escreval("Sua resposta está errada, a capital do Brasil é Brasília :(")
   fimse
Fimalgoritmo