Algoritmo "Lista 3-5"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jefferson leonardo
// Data atual  : 19/10/2021
Var
   n :inteiro
Inicio
   escreva("Digite um número inteiro: ")
   leia(n)
   escreval
   se (n%4=0) e (n%5=0)entao
   escreval("O número",n," é divisível por 4 e 5")
   senao
   escreval("O número",n," não é divisível por 4 e 5")
   fimse
Fimalgoritmo