Algoritmo "Lista 4-9"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jefferson Leonardo
// Data atual  : 21/10/2021
Var
   x, y:inteiro
Inicio
   x <- 2
   y <- 1
   enquanto (x<=9) faca
      enquanto (y<=10) faca
         escreval(x," .", y, " =", x*y)
         y <- y + 1
      fimenquanto
      escreval
      y <- 1
      x <- x + 1
   fimenquanto
Fimalgoritmo