Algoritmo "Lista 1-5"
// Disciplina   :[Linguagem e Lógica de Programação]
// Professor   : Natália dos Santos Grillo
// Descrição   : Calcular o aumento de 15% no salário
// Data atual  : 13/10/2021
Var
sal, saltotal:real

Inicio
escreva("Digite o valor do salário: ")
leia(sal)
saltotal<- (sal*1.15)
escreval
escreval("O salário com o aumento de 15% é:",saltotal," reais")

Fimalgoritmo