Algoritmo "Lista 1-3"
// Disciplina   :[Linguagem e Lógica de Programação]
// Professor   : Natália dos Santos Grillo
// Descrição   : Converter dólar para real
// Data atual  : 13/10/2021
Var
dolar, reais:real

Inicio
escreva("Digite quantos dólares quer converter:")
leia(dolar)
reais<- (dolar*1.72)
escreval
escreval("Essa quantia de dólar corresponde a",reais," reais")

Fimalgoritmo