Algoritmo "Lista 1-6"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jefferson Leonardo
// Descrição   : Calcular o quadrado e a raiz
// Data atual  : 14/10/2021
Var
   f, c, result:real

Inicio
   escreva("Digite uma temperatura em Fahrenheit: ")
   leia(f)
   c<- (f-32)*5/9
   escreval
   escreval("Essa temperatura equivale a",c," graus Celsius")

Fimalgoritmo