Algoritmo "Lista 1-4"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Natália dos Santos Grillo
// Descrição   : Calcular o antecessor e o sucessor
// Data atual  : 13/10/2021
Var
ant, suc, numero:real

Inicio
escreva("Digite um número qualquer: ")
leia(numero)
ant <- numero-1
suc <- numero+1
escreval("===============================")
escreval("O antecessor desse número é:",ant)
escreval("O sucessor desse número é:",suc)
Fimalgoritmo