Algoritmo "Lista 1-1"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Natália dos Santos Grillo
// Descrição   : Apresentar dados informados
// Data atual  : 13/10/2021
Var
nome, sexo:caractere

Inicio
escreva("Digite seu nome completo: ")
leia(nome)
escreva("Digite seu sexo: ")
leia(sexo)
escreval("==========================")
escreval("Confirmado! Seu nome completo é ", nome," e seu sexo é ",sexo)
Fimalgoritmo