Algoritmo "Lista 1-7"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Natália dos Santos Grillo
// Descrição   : Calcular a média aritmética
// Data atual  : 13/10/2021
Var
n1,n2,n3,media: real

Inicio
escreva("Digite o primeiro número: ")
leia(n1)
escreva("Digite o segundo número: ")
leia(n2)
escreva("Digite o terceiro número: ")
leia(n3)
media<- (n1+n2+n3)/3
escreval
escreval("A média aritmética desses valores é:",media)
Fimalgoritmo