Algoritmo "Lista 1-9"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jefferson Leonardo
// Descrição   : Calcular o quadrado e a raiz quadrada
// Data atual  : 14/10/2021
Var
   n1, quadrado, raiz:real

Inicio
   escreva("Digite um número qualquer: ")
   leia(n1)
   quadrado <-n1^2
   raiz <- raizq(n1)
   escreval
   escreval("O número apresentado é",n1,", o quadrado dele é",quadrado,", e sua raiz quadrada é",raiz)
Fimalgoritmo