Algoritmo "Lista 2-5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jefferson Leonardo
// Descrição   : Calcular o volume
// Data atual  : 18/10/2021
Var
   r, h, V:real

Inicio
   escreva("Digite o valor do raio da lata de óleo: ")
   leia(r)
   escreva("Digite o valor da altura da lata de óleo: ")
   leia(h)
   V <-3.14*(r^2)*h
   escreval
   escreval("O valor do volume da lata de óleo é",V)
Fimalgoritmo